Revert to Jetty 9 config and dependency
Without the configuration, there is a class incompatibility causing
issues with mail sending:

    java.lang.NoClassDefFoundError: javax/activation/DataSource