Override dependency version for Bouncy Castle
This fixes runtime issues caused by having different versions of Bouncy
Castle modules on the classpath.

Error:
    java.lang.NoSuchFieldError: <some crypto algorithm>
      at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>